"""add lid field to users

Revision ID: 16519707cd48
Revises: 4a358dcb9542
Create Date: 2025-09-27 09:19:20.731999

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16519707cd48"
down_revision = "4a358dcb9542"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("lid", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_users_lid"), "users", ["lid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_lid"), table_name="users")
    op.drop_column("users", "lid")
    # ### end Alembic commands ###
