"""Add user_settings table

Revision ID: 68f0cded3490
Revises: 16519707cd48
Create Date: 2025-09-29 16:21:52.154955

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68f0cded3490"
down_revision = "16519707cd48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("daily_reports_enabled", sa.Boolean(), nullable=False),
        sa.Column("daily_reports_time", sa.Time(), nullable=False),
        sa.Column("commitment_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("commitment_alerts_time", sa.Time(), nullable=False),
        sa.Column("google_calendar_connected", sa.Boolean(), nullable=False),
        sa.Column("google_calendar_email", sa.String(length=255), nullable=True),
        sa.Column(
            "google_calendar_last_sync", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("sync_transactions_enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_commitments_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_settings_id"), "user_settings", ["id"], unique=False)
    op.drop_index("ix_expressions_embeddings_id", table_name="expressions_embeddings")
    op.drop_table("expressions_embeddings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expressions_embeddings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("document", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="expressions_embeddings_pkey"),
    )
    op.create_index(
        "ix_expressions_embeddings_id", "expressions_embeddings", ["id"], unique=False
    )
    op.drop_index(op.f("ix_user_settings_id"), table_name="user_settings")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
